import 'babel-polyfill';
require('es5-shim');
require('es5-shim/es5-sham');
require('console-polyfill');
require('jsplumb');
require('./Constants');
require('./core/GearType');
require('./core/GearArray');
require('./core/GearJson');
require('./utils/DomPropertiesToReactProperties');